# Generated by Django 4.1.5 on 2023-02-04 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomebanco', models.CharField(max_length=225)),
                ('numerobanco', models.FloatField()),
                ('descricao', models.CharField(max_length=225)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bancos_cadastrados_bancoCental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispb', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('code', models.FloatField()),
                ('fullName', models.CharField(max_length=250)),
                ('lastUpdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nometitular', models.CharField(max_length=225)),
                ('debtocredito', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('OS DOIS', 'Os dois')], max_length=20)),
                ('createdAt', models.DateTimeField()),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.bancos')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida')], max_length=20)),
                ('createdAt', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Limites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cartao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banco.cartoes')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField()),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.cartoes')),
                ('seguiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.seguimento')),
            ],
        ),
        migrations.CreateModel(
            name='Extrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('PIX', 'Pix')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField()),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.cartoes')),
                ('seguiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.seguimento')),
            ],
        ),
        migrations.AddField(
            model_name='bancos',
            name='banks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.bancos_cadastrados_bancocental'),
        ),
        migrations.AddField(
            model_name='bancos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
