# Generated by Django 4.1.5 on 2023-01-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signup_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
