# Generated by Django 4.1.5 on 2023-01-25 19:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, null=True)),
                ('modelo', models.CharField(max_length=50, null=True)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('apelido', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2023, 1, 25, 19, 19, 17, 719207))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quilometragem_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_litro', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tanque_cheio', models.BooleanField(null=True)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField()),
                ('seguimentos', models.CharField(default='gasolina', max_length=225)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cars', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fuel.cars')),
            ],
        ),
    ]
